name: Go Security Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 1 * *"
  pull_request:

jobs:
  security:
    name: Run security scans
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      
    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    # 3. Install gosec
    - name: Install gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    # 4. Install govulncheck
    - name: Install govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: cd frontend && npm install

    # 5. Download Go modules
    - name: Download dependencies
      run: go mod download

    # 6. Run gosec
    - name: Run gosec
      run: gosec ./...

    # 7. Run govulncheck
    - name: Run govulncheck
      run: cd webapi && govulncheck ./...

    - name: Run npm audit
      run: cd frontend && npm audit --omit=dev --audit-level=high

    - name: Run npm eslint

      run: cd frontend && npx eslint "**/*.{js,mjs,cjs,vue}" --max-warnings=0
